CREATE TABLE IF NOT EXISTS USER
(
  USER_ID NUMBER(5) NOT NULL,
  USER_NAME VARCHAR(36) NOT NULL,
  ENCRYPTED_PASSWORD VARCHAR(128) NOT NULL,
  ENABLED NUMBER(1) NOT NULL,
  CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
  CONSTRAINT USER_UK UNIQUE (USER_NAME)
);

INSERT INTO USER (USER_ID, USER_NAME, ENCRYPTED_PASSWORD, ENABLED)
VALUES (1, 'user1', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);

INSERT INTO USER (USER_ID, USER_NAME, ENCRYPTED_PASSWORD, ENABLED)
VALUES (2, 'user2', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);

INSERT INTO USER (USER_ID, USER_NAME, ENCRYPTED_PASSWORD, ENABLED)
VALUES (3, 'user3', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', 1);


CREATE TABLE IF NOT EXISTS ROLE
(
  ROLE_ID   NUMBER(19) NOT NULL,
  ROLE_NAME VARCHAR2(30) NOT NULL,
  CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_ID),
  CONSTRAINT ROLE_UK UNIQUE (ROLE_NAME)
) ;

INSERT INTO ROLE (ROLE_ID, ROLE_NAME)
VALUES (1, 'ROLE_USER');


CREATE TABLE IF NOT EXISTS USER_ROLE
(
  ID      NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  ROLE_ID NUMBER(19) NOT NULL,
  CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID),
  CONSTRAINT USER_ROLE_UK UNIQUE (USER_ID,ROLE_ID),
  CONSTRAINT USER_ROLE_FK1 FOREIGN KEY (USER_ID)
    REFERENCES USER (USER_ID),
  CONSTRAINT USER_ROLE_FK2 foreign key (ROLE_ID)
    REFERENCES ROLE (ROLE_ID)
);

INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID)
VALUES (1, 1, 1);

INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID)
VALUES (2, 2, 1);

INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID)
VALUES (3, 3, 1);


CREATE TABLE IF NOT EXISTS CLIENT
(
  ID NUMBER AUTO_INCREMENT NOT NULL,
  FIRST_NAME VARCHAR2(255) NOT NULL,
  LAST_NAME VARCHAR2(255) NOT NULL,
  USERNAME VARCHAR2(255) NOT NULL,
  EMAIL VARCHAR2(255),
  ADDRESS VARCHAR2(255) NOT NULL,
  COUNTRY VARCHAR2(100) NOT NULL,
  CONSTRAINT CLIENT_PK PRIMARY KEY (ID)
);

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, ADDRESS, COUNTRY) values ('Redi','Kotkas', 'redikotkas', 'redi@gmail.com', 'Tallinn', 'Estonia');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, ADDRESS, COUNTRY) values ('John','Smith', 'johnsmith', 'john@gmail.com', 'Tallinn', 'Estonia');


CREATE TABLE IF NOT EXISTS USER_CLIENT
(
  ID NUMBER AUTO_INCREMENT NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  CLIENT_ID NUMBER(19) NOT NULL,
  CONSTRAINT USER_CLIENT_PK PRIMARY KEY (ID),
  CONSTRAINT USER_CLIENT_UK UNIQUE (USER_ID,CLIENT_ID),
  CONSTRAINT USER_CLIENT_FK1 FOREIGN KEY (USER_ID)
    REFERENCES USER (USER_ID),
  CONSTRAINT USER_CLIENT_FK2 FOREIGN KEY (CLIENT_ID)
    REFERENCES CLIENT (ID)
);

INSERT INTO USER_CLIENT (ID, USER_ID, CLIENT_ID) VALUES ( 1, 1, 1 );
INSERT INTO USER_CLIENT (ID, USER_ID, CLIENT_ID) VALUES ( 2, 1, 2 );


CREATE TABLE IF NOT EXISTS COUNTRY(
  ID NUMBER(5),
  COUNTRY VARCHAR2(100)
);

INSERT INTO COUNTRY VALUES ( 1, 'Estonia' );
INSERT INTO COUNTRY VALUES ( 2, 'Latvia' );
INSERT INTO COUNTRY VALUES ( 3, 'Lithuania' );
INSERT INTO COUNTRY VALUES ( 4, 'Finland' );
INSERT INTO COUNTRY VALUES ( 5, 'Sweden' );